version: '1'
services:
  immudb:
    image: codenotary/immudb:latest
    ports:
      - 3322:3322
      - 8080:8080
  geoserver:
    build:
      context: .
      dockerfile: build/geoserver/Dockerfile
    ports:
      - 7070:8080
    environment:
      - EXTRA_JAVA_OPTS=-Xms1G -Xmx2G
    volumes:
      - ./geoserver_data:/opt/geoserver_data/:Z
      - ./additional_libs:/opt/additional_libs:Z # by mounting this we can install libs from host on startupopt/
    depends_on:
      - immudb
  location-registry:
    build:
       context: .
       dockerfile: build/location-registry/Dockerfile
    ports:
      - 9090:8080
      - 5005:5005
    environment:
      _JAVA_OPTIONS: >
              -Xdebug
              -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    depends_on:
      - immudb
